# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Computer', max_length=32)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('last_seen', models.DateTimeField(verbose_name='date modified')),
                ('cpu', models.CharField(default='Unknown', max_length=128)),
                ('mem_type', models.CharField(default='Unknown', max_length=16)),
                ('mem_amount', models.IntegerField(default=0)),
                ('gpu', models.CharField(default='Unknown', max_length=64)),
                ('os', models.CharField(choices=[('Unknown', 'Unknown'), ('Linux', 'Linux'), ('BSD', 'BSD'), ('Windows', 'Windows'), ('Mac OS X', 'Mac OS X')], default='Unknown', max_length=16)),
                ('type', models.CharField(choices=[('Unknown', 'Unknown'), ('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Server', 'Server')], default='Unknown', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='OSDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('arch', models.CharField(default='amd64', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('location', models.CharField(default='Earth', max_length=32)),
                ('gender', models.CharField(default='Unknown', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.OSDistribution'),
        ),
        migrations.AddField(
            model_name='installation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
