# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Computer', max_length=32)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('last_seen', models.DateTimeField(verbose_name='date modified')),
                ('cpu', models.CharField(default='Unknown', max_length=128)),
                ('mem_type', models.CharField(default='Unknown', max_length=16)),
                ('mem_amount', models.IntegerField(default=0)),
                ('gpu', models.CharField(default='Unknown', max_length=64)),
                ('os', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Linux'), (2, 'BSD'), (3, 'Windows'), (4, 'Mac OS X')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Desktop'), (2, 'Laptop'), (3, 'Server')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('location', models.CharField(default='Earth', max_length=32)),
                ('gender', models.CharField(default='Unknown', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
